language: ruby
rvm:
  - 1.9.3-p392
env:
  - GOVUK_APP_DOMAIN=dev.gov.uk RUBYOPT="-rpsych" FACTER_govuk_platform=test
services:
  - mongodb
script:
  - bundle exec rake db:mongoid:drop
  - bundle exec rake test
bundler_args: --without=development
branches:
  except:
    - release
notifications:
  email: false
